spring:
  application:
    name: cloudapi
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    hikari:
      schema: public
      connection-timeout: 10000
  jpa:
    generate-ddl: true
    open-in-view: false
springdoc:
  swagger-ui:
    url: /openapi.yaml
server:
  port: 8085
jwt:
  lifetime: 180000000
  sign-key: 20E6373E53AA93FFBAC681D68D12879819CF6641FB1C9393785C09182DF0CA36
